### BELAJAR PYTHON dalam STUDI KASUS KRIPTOGRAFI KLASIK   
#### Cipher Substitusi abjad tunggal

Suatu pesan dalam plainteks dapat disamarkan sedemikian rupe menjadi cipherteks yang tidak dapat dimengerti maknanya untuk menjaga keamanan pesan atau kerahasiaan terhadap orang yang tidak berhak. Misalnya bahasa percakapan yang disandikan dengan mengganti huruf konsonan, dengan algoritma cipher hanacaraka, seperti "matamu" menjadi "dagadu".  
Penukaran dilakukan antar baris genap dan ganjil aksara Jawa, atau digeser 10 aksara dari 20 aksara Jawa, **ha na ca ra ka da ta sa wa la pa dha ja ya nya ma ga ba tha nga**, yaitu
- ha na ca ra ka <--> pa dha ja ya nya
- da ta sa wa la <--> ma ga ba tha nga

Paniradya Kaistimewan, lembaga yang mengurusi program keistimewaan Yogyakarta, mengungkapkan hal tersebut di Twitter @PaniradyaJogja, Kamis (28/5/2020). Menurut keterangannya, Boso Walikan Jogja *"sudah dipakai ketika masa penjajahan, pernah menjadi bahasa Gaul di era 1990an, merupakan bahasa terenkripsi dengan metode penukaran pada aksara jawa."*   
(dikutip dari suarajogja.id) [boso walikan jogja](https://jogja.suara.com/read/2020/05/29/210014/ada-rumusnya-ini-asal-usul-kata-dagadu-hingga-dab-dalam-boso-walikan-jogja)   
Secara matematis, enkripsi/dekripsi **Bosowalikan Cipher** dinyatakan dalam persamaan
> *c = (p + 10) modulo 20*
>
> *p = (c + 10) modulo 20*   


![Boso walikan](https://media.suara.com/pictures/original/2020/05/29/90190-boso-walikan-jogja-twitteratpaniradyajogja.jpg)


Bosowalikan Cipher menggunakan aturan algoritma tanpa kunci yang keamanannya terletak pada kerahasiaan algoritmanya. Kriptografi telah berkembang dengan penggunaan kunci sehingga walaupun algoritmanya diketahui umum tetapi keamanannya tetap terjaga karena pada kerahasiaan kuncinya.

Algoritma seperti Bosowalikan Cipher yang menggunakan substitusi abjad tunggal yang sederhana (*simple-substitution cipher*), fungsi satu-ke-satu yang statis, tidak aman, karena bisa dianalisa berdasarkan pola-pola dalam bahasa yang digunakan atau analisa frekuensi, apalagi jika hanya huruf konsonan yang diganti, huruf vokal tetap sama. 

Struktur aksara Jawa berbeda dengan abjad Latin, sehingga kita melakukan penyesuaian awal dengan mengganti aksara dha, nya, tha, nga menjadi huruf f, q, v, x yang tidak digunakan. Dengan demikian daftar hurufnya ialah   
> h n c r k d t s w l p f j y q m g b v x


Adapun huruf-huruf vokal atau tanda baca, tetap tidak diganti.

Algoritma cipher bosowalikan menjadi sbb:   
> lakukan penyesuaian aksara khusus menjadi huruf yang tersisa   
> loop untuk setiap huruf
> > jika huruf vokal atau spasi maka output sama, continue ke berikutnya   
> > substitusi dengan huruf pada indeks + 10 modulo 20   

> kembalikan simbol huruf f,g,v,x ke aksara awal dh, ny. th. ng
   
Algoritma yang sama digunakan bolak balik balik untuk proses encipher maupun decipher.

In [2]:
# PROGRAM (1) Cipher Bosowalikan Jogja 
# tabel huruf yang disubstitusi
tabel_walik = 'hncrkdtswlpfjyqmgbvx'

# pengkode, lihat PEP 378
aksara2 = 'f','q','v','x','dh','ny','th','ng'
hurufganti = '%@%','%#%','%$%','%^%','f','q','v','x'

def encode(words):
    for idx, hrf in enumerate(aksara2):
        words = words.replace(hrf,hurufganti[idx])
    return words

def dekode(words):
    for idx, hrf in enumerate(hurufganti[::-1]):
        words = words.replace(hrf,(aksara2[::-1])[idx])
    return words


print('Cipher Bosowalikan')
plainteks = input("masukkan kalimat:")

cipherteks = ""
#print(encode(plainteks))

for ch in encode(plainteks):
    if ch not in tabel_walik:
        cipherteks += ch
        continue
    idx = tabel_walik.find(ch)
    idx = (idx + 10) % 20
    cipherteks += tabel_walik[idx]

#print(cipherteks)
print(dekode(cipherteks))


Cipher Bosowalikan


masukkan kalimat: mas, kowe arep nang ngendi? dhal fqvx.


dab, nyothe ayeh dhal ledhmi? nang fqvx.


Implementasi penyamaran teks menggunakan metoda susbstitusi abjad tunggal sebenarnya sederhana, hanya mencari indeks setiap karakter dalam tabel, mengubah index, lalu menampilkan karakter pada indeks tersebut.
Sedikit komplikasi karena terdapat aksara yang tampil sebagai huruf ganda yang perlu dikodekan tetapi perlu penanganan lebih lanjut apabila teks aslinya ternyata mengandung huruf-huruf Latin yang digunakan sebagai kode huruf ganda.

Cipher substitusi abjad tunggal jelek keamanannya, contohnya cipher buatan kaisar Romawi Julius Caesar, dan cipher buatan ratu Skotlandia Mary Stuart. Pola kata-kata terlihat jelas sehingga mudah ditebak/didekripsi oleh pemecah kode ulung menggunakan analisis frekuensi kemunculan huruf-huruf dalam suatu bahasa.

#### Cipher substitusi abjad banyak

Metoda pergeseran huruf pada substitusi abjad tunggal menggunakan rumus pergeseran yang konstan, misalnya **c = (p+10) mod 20** tetapi pada substitusi abjad ganda setiap hurufnya digeser secara berbeda menggunakan suatu pola kunci, misalnya kunci=10,11,12,13,4,5,6,7, maka pergeseran yang dilakukan sesuai kunci satu per satu lalu berulang setelah panjang kunci berakhir. Makin panjang kuncinya maka makin tinggi keamanannya. Kode Python berikut mengilustrasikan jenis cipher ini.

In [26]:
# mendefinisikan tabel kunci
import random
panjang = 99
for i in range(panjang):
    print(random.randint(101,999) % 37,end=', ')


18, 28, 24, 32, 2, 30, 0, 3, 2, 34, 33, 28, 29, 23, 9, 35, 31, 35, 21, 9, 20, 36, 18, 16, 2, 7, 12, 2, 7, 10, 4, 11, 28, 31, 23, 35, 18, 36, 31, 22, 16, 18, 12, 3, 1, 36, 32, 23, 5, 12, 22, 29, 20, 1, 17, 17, 25, 13, 23, 4, 1, 16, 33, 29, 23, 29, 0, 4, 15, 21, 1, 1, 11, 28, 3, 19, 34, 27, 32, 20, 25, 26, 20, 36, 10, 30, 24, 12, 35, 35, 12, 12, 25, 1, 29, 7, 2, 21, 7, 

In [30]:
# PROGRAM (2) substitusi abjad banyak
# definisi ruang abjad
abjadnya ='1234567890 qwertyuiopasdfghjklzxcvbnm' # 37 simbol angka/huruf termasuk spasi
# kunci random tidak dapat dibuat ulang, setiap di-run hasilnya berbeda, maka harus dicopas hardcoded
kunci = 25, 19, 25, 17, 32, 15, 5, 11, 22, 0, 8, 25, 34, 34, 2, 20, 10, 18, 16, 27, 30, 36, \
34, 7, 8, 1, 32, 17, 27, 28, 21, 34, 8, 30, 0, 24, 2, 7, 4, 22, 20, 35, 25, 31, 16, 24, 36, \
18, 27, 15, 12, 15, 29, 27, 29, 36, 28, 34, 33, 27, 16, 0, 15, 31, 0, 31, 23, 27, 9, 22, 25, \
11, 1, 26, 12, 7, 32, 15, 33, 30, 18, 16, 32, 10, 16, 10, 5, 35, 16, 19, 30, 20, 22, 25, 28, \
20, 7, 0, 15,
keylen = len(kunci)

# 
plainteks = input('masukan plainteks:')
ciphteks = ''

for nmr, c in enumerate(plainteks):
    if c not in abjadnya:
        ciphteks += c
        continue
    idx = abjadnya.find(c)
    idx = (idx + kunci[nmr % keylen]) %37
    ciphteks += abjadnya[idx]

print(ciphteks)

tekshasil = ''
for nmr, c in enumerate(ciphteks):
    if c not in abjadnya:
        tekshasil += c
        continue
    idx = abjadnya.find(c)
    idx = (idx - kunci[nmr % keylen]) %37
    tekshasil += abjadnya[idx]

print(tekshasil)



masukan plainteks: besok pagi segera laksanakan perintah komandan


sc mdggc ii  stbxk9qaai6llyt1qbqhkt9kuc5oodu1s
besok pagi segera laksanakan perintah komandan


Pola kata-kata tidak terlihat lagi dalam penyamaran abjad banyak, karena rumus pergeserannya berubah-ubah setiap hurufnya. Cipher klasik sejenis ini lumayan kuat, hanya tidak boleh digunakan secara berulang-ulang dan pola kunci harus lebih panjang daripada teks aslinya.  
Kunci yang panjang tentunya menyulitkan jika harus dikirim maka perlu ditambahkan suatu identifikasi kunci, dan kunci dapat dibangun dan digunakan sesuai identifikasinya. Identitas kunci ini dikirim dengan metoda cipher modern asimetris private/publik key; nanti kita bahas mengenai protokol pertukaran kunci Diffie-Hellman.    


Cipher klasik berkembang dengan metoda pergeseran perkalian selain metoda pergeseran tambah-kurang.    
> c = (Fp + A) mod n   
> p = (F'(c - A) mod n

Faktor F dan F' adalah pasangan yang jika dikalikan menghasilkan nilai 1 dalam medan n yaitu dengan perkalian modulo aritmetika. Dalam medan n, semua anggotanya bernilai dari 0 sampai n-1, dan baik penjumlahan maupun perkalian dalam konteks itu selalu menghasilkan nilai yang berada dalam medan n, tidak lompat keluar. Agar mudah kita akan menggunakan angka prima sebagai n sehingga semuanya relatif prima terhadap n, dan semuanya memiliki pasangan balikan modulo (modulo inverse) berbeda, kecuali nol tidak ada, satu dan n-1 (atau minus satu) hasilnya sama.

In [9]:
# PROGRAM (3) mencari modulo inverse
# Cryptomath Module
# https://www.nostarch.com/crackingcodes (BSD Licensed)


def gcd(a, b):
    # Return the Greatest Common Divisor of a and b using Euclid's Algorithm
    while a != 0:
        a, b = b % a, a
    return b


def findModInverse(a, m):
    # Return the modular inverse of a % m, which is
    # the number x such that a*x % m = 1

    if gcd(a, m) != 1:
        return None # No mod inverse exists if a & m aren't relatively prime.

    # Calculate using the Extended Euclidean Algorithm:
    u1, u2, u3 = 1, 0, a
    v1, v2, v3 = 0, 1, m
    while v3 != 0:
        q = u3 // v3 # Note that // is the integer division operator
        v1, v2, v3, u1, u2, u3 = (u1 - q * v1), (u2 - q * v2), (u3 - q * v3), v1, v2, v3
    return u1 % m

m = 37
mkey_pairs = []
for a in range(2,m-1):
    ainv = findModInverse(a,m)
    mkey_pairs.append((a,ainv))
print(mkey_pairs)

[(2, 19), (3, 25), (4, 28), (5, 15), (6, 31), (7, 16), (8, 14), (9, 33), (10, 26), (11, 27), (12, 34), (13, 20), (14, 8), (15, 5), (16, 7), (17, 24), (18, 35), (19, 2), (20, 13), (21, 30), (22, 32), (23, 29), (24, 17), (25, 3), (26, 10), (27, 11), (28, 4), (29, 23), (30, 21), (31, 6), (32, 22), (33, 9), (34, 12), (35, 18)]


In [32]:
# PROGRAM (4) Affine Cipher plus polyalphabetic
add_keys = kunci # lihat tabel kunci yang didefinisikan di atas
alen = len(add_keys)
plainteks = "Affine Cipher adalah jenis cipher substitusi monoalphabetic, " \
"di mana setiap huruf dalam alfabet dipetakan ke padanan numeriknya, "\
"dienkripsi menggunakan fungsi matematika sederhana, dan dikonversi kembali menjadi huruf."

medan = 37
mlen = len(mkey_pairs)
# proses abjad banyak dilakukan dengan fungsi map dan enumerate
# argumen yang dikirimkan berupa tuple berisi nomor urut, dan hurufnya
def polyaffine_encrypt(t):
    idx = t[0]
    huruf = t[1]
    p = abjadnya.find(huruf)
    if (-1 == p): # jika tidak dalam termasuk abjadnya, 
        return huruf # kembalikan tanpa proses
    c = ( mkey_pairs[idx % mlen][0] * p + add_keys[idx % alen] ) % medan
    return abjadnya[c]

def polyaffine_decrypt(t):
    idx = t[0]
    huruf = t[1]
    c = abjadnya.find(huruf)
    if (-1 == c): # jika tidak dalam termasuk abjadnya, 
        return huruf # kembalikan tanpa proses
    p = ( mkey_pairs[idx % mlen][1] * (c - add_keys[idx % alen] )) % medan
    return abjadnya[p]


affpoly_teks = "".join(map(polyaffine_encrypt,enumerate(plainteks)))
print(affpoly_teks)
teks_aslinya = "".join(map(polyaffine_decrypt,enumerate(affpoly_teks)))
print()
print(teks_aslinya)

Au vpcqCunf09m65irlikkexc4ypwo3o4 82j7p1l4d8gq7gn3ygxf13i4r,12196alslr4wngfdvuylaizbp3sdbprji75rx4h qpma8ix374ekjeiuzo1q1cvdjg9,wso54mo4 vpvl6tot2x51xprtovn149kkeg9c8q9v6i484ulnti,gn9dshhzlg7gkd8i8sc1xwtc4erfd2ze4szuo.

Affine Cipher adalah jenis cipher substitusi monoalphabetic, di mana setiap huruf dalam alfabet dipetakan ke padanan numeriknya, dienkripsi menggunakan fungsi matematika sederhana, dan dikonversi kembali menjadi huruf.


Sudah cantik nampaknya metoda yang kita gunakan, tinggal perlu memperpanjang kunci multiplikatif dan kunci additifnya.    

#### Memperpanjang kunci multiplikatif

Kunci yang kita gunakan ibarat roda yang diputar terus menerus, makin besar rodanya berarti makin panjang kuncinya sebelum berulang dari awal lagi. Jika kita gunakan dua roda yang tidak sama besarnya (tidak sama panjang) maka kuncinya menjadi kombinasi keduanya dan total panjangnya menjadi perkalian panjangnya dibagi PPB (**p**embagi **p**ersekutuan ter**b**esar).   
Tetapi pertama-tama roda awalnya dibuat agak besar yaitu dengan memperbesar medan Galois yang digunakan supaya pasangan kuncinya lebih banyak. Nilai medan yang dipilih ialah angka prima 67 yang cukup untuk menampung abjad huruf kecil, kapital, angka, dan beberapa tanda baca.

In [6]:
# PROGRAM (5) kunci_multiplikatif lebih panjang
gf = 67
abjadnya = 'abcdefghijklmnopqrstuvwxyz,QWERTYUIOPASDFGHJKLZXCVBNM.1234567890?! ' # 67 karakter
mkey_pairs = []
for a in range(2,gf-1):
    ainv = findModInverse(a,gf)
    mkey_pairs.append((a,ainv))
print(mkey_pairs)
print(len(mkey_pairs))

[(2, 34), (3, 45), (4, 17), (5, 27), (6, 56), (7, 48), (8, 42), (9, 15), (10, 47), (11, 61), (12, 28), (13, 31), (14, 24), (15, 9), (16, 21), (17, 4), (18, 41), (19, 60), (20, 57), (21, 16), (22, 64), (23, 35), (24, 14), (25, 59), (26, 49), (27, 5), (28, 12), (29, 37), (30, 38), (31, 13), (32, 44), (33, 65), (34, 2), (35, 23), (36, 54), (37, 29), (38, 30), (39, 55), (40, 62), (41, 18), (42, 8), (43, 53), (44, 32), (45, 3), (46, 51), (47, 10), (48, 7), (49, 26), (50, 63), (51, 46), (52, 58), (53, 43), (54, 36), (55, 39), (56, 6), (57, 20), (58, 52), (59, 25), (60, 19), (61, 11), (62, 40), (63, 50), (64, 22), (65, 33)]
64


In [31]:
# PROGRAM (6) kunci 3 roda
len_satu = 64
len_dua = 0
len_tiga = 0
for n in range(64,2,-1):
    if gcd(n,len_satu) == 1:
        if 0 == len_dua :
            len_dua = n
            continue
        if 0 == len_tiga and 1 == gcd(n,len_dua) :
            len_tiga = n
            break
print(f'{len_satu=}, {len_dua=}, {len_tiga=}')    
len_keys = len_satu * len_dua * len_tiga 

print(f'panjang total kunci kombinasi {len_keys:,}')

print('jika dibuat panjang tabel additif 1063')
print(f'dan gcd-nya {gcd(1063, len_keys)} satu, maka grand total panjang perulangan enkripsi {1063*len_keys:,}')

len_satu=64, len_dua=63, len_tiga=61
panjang total kunci kombinasi 245,952
jika dibuat panjang tabel additif 1063
dan gcd-nya 1 satu, maka grand total panjang perulangan enkripsi 261,446,976


Jadi roda satu atau rotor satu (meminjam istilah pada Enigma Cipher) berisi pasangan kunci yang lengkap, sedangkan rotor kedua dan ketiga tidak lengkap, lebih pendek. Kunci kombinasi adalah perkalian kunci pada ketiga rotor. Ketika rotor ketiga restart rotor kedua dan kesatu masih meneruskan putarannya, maka hasil perkaliannya akan memiliki pola (beberapa angka berturutan) yang berbeda dibandingkan ketika start bareng, dan seterusnya hingga akhirnya sampai pada key ke-245952, lalu pada key ke-245953 polanya kembali ke awal start bareng.   
Implementasinya ialah dengan menggunakan aritmetika modulo pada indeks dari tabel kunci, yang berputar-putar dalam batasan medan yang digunakan.

In [35]:
# PROGRAM (7) mengakses key kombinasi
idx = 0,1,2,3,4, 60,61,62,63,64, 61*63, 61*63+1, 61*63*64-1, 61*63*64, 61*63*64+1, 61*63*64+2, 61*63*64+3, 61*63*64+4
keys = mkey_pairs
for i in idx:
    print((keys[i % len_satu][0] * keys[i % len_dua][0] * keys[i % len_tiga][0]) % gf, end='  ')
print()
for i in idx:    
    print((keys[i % len_satu][1] * keys[i % len_dua][1] * keys[i % len_tiga][1]) % gf, end='  ')
    

8  27  64  58  15  9  32  27  51  30  20  54  37  8  27  64  58  15  
42  5  22  52  9  15  44  5  46  38  57  36  29  42  5  22  52  9  

Prinsipnya ada dua patokan untuk pemakaian kunci multiplikatif yang bagus, yaitu kesatu kunci harus panjang sekali, dan kedua pola kunci yang sama jangan dipakai ulang. Prinsip kesatu sudah tercapai, jika masih kurang rotor masih bisa ditambah dengan mudah. Prinsip kedua, berarti kita harus memiliki metoda mengacak pola mkey_pairs lalu mengambil salah satunya secara konsisten dengan angka identifikasi saja. Mari tengok bagaimana kita dapat menggapai target multi mkeys yang diperlukan.   

Masih dengan metoda penggunaan roda modulo, kita memerlukan 2 kali 64 buah roda yang masing-masing mempunyai jumlah gigi angka prima yang berbeda satu sama lainnya. Kita buat dulu roda-roda modulonya.

In [109]:
# PROGRAM (8)
# tapis eratosthenes
# membuat roda modulo
from array import array

def primes_sieve(limit: int) -> tuple:
    # byte array allocation, 1 byte per item for boolean result each
    sieve = array('b', [True] * limit)
    sieve[0] = sieve[1] = False  # zero and one are not prime numbers.
    for start in range(2, int(limit ** 0.5) + 1):
        if not sieve[start]:
            continue
        idx = start ** 2
        while idx < limit:
            sieve[idx] = False
            idx += start
    return [i for i,p in enumerate(sieve) if p]

primes = primes_sieve(2022)
n = len(primes)
aprimes = primes[10:74]
bprimes = primes[n-128:n:2]

print(aprimes)
print(bprimes)
total=1
for n in bprimes:
    total *= n
print(f'jumlah variasi = {total:.1E}')
print(f'tepatnya sebanyak {total:,}')



[31, 37, 41, 43, 47, 53, 59, 61, 67, 71, 73, 79, 83, 89, 97, 101, 103, 107, 109, 113, 127, 131, 137, 139, 149, 151, 157, 163, 167, 173, 179, 181, 191, 193, 197, 199, 211, 223, 227, 229, 233, 239, 241, 251, 257, 263, 269, 271, 277, 281, 283, 293, 307, 311, 313, 317, 331, 337, 347, 349, 353, 359, 367, 373]
[1063, 1087, 1093, 1103, 1117, 1129, 1153, 1171, 1187, 1201, 1217, 1229, 1237, 1259, 1279, 1289, 1297, 1303, 1319, 1327, 1367, 1381, 1409, 1427, 1433, 1447, 1453, 1471, 1483, 1489, 1499, 1523, 1543, 1553, 1567, 1579, 1597, 1607, 1613, 1621, 1637, 1663, 1669, 1697, 1709, 1723, 1741, 1753, 1777, 1787, 1801, 1823, 1847, 1867, 1873, 1879, 1901, 1913, 1933, 1951, 1979, 1993, 1999, 2011]
jumlah variasi = 2.5E+203
tepatnya sebanyak 247,081,745,958,054,367,555,907,837,718,941,038,874,521,946,309,503,968,472,193,864,012,375,131,307,434,443,061,017,804,722,199,766,123,349,448,371,515,168,112,378,052,705,605,158,628,273,976,396,945,354,688,267,345,761,269,129,187,454,027,340,898,716,017,269,237,5

Kelompok roda pertama (aprimes) menentukan pengacakan dan kelompok roda kedua (bprimes) menentukan panjang perulangan. Tabel pengacak tersebut dirumuskan sebagai berikut   
> Xkn = ((Ak * n) mod Bk) mod p    
dimana   
> > n = nomor variasi pengacak yang dipilih   
> > k = 0 ~ 63   
> > p = panjang mkey_pairs = 64   


In [7]:
# PROGRAM (9)
# membuat tabel pengacak dan tabel mkey yang baru
variasi = input('masukan angka pilihan variasi tabel')
variasi = int(variasi) % total # nomor variasi yang valid < total 2.47E+203
p = 64
new_mkey_pairs = []
for k in range(p):
    x = (( aprimes[k] * variasi ) % bprimes[k] ) % p 
    new_mkey_pairs.append(mkey_pairs[x])
print(new_mkey_pairs)

masukan angka pilihan variasi tabel 12345678901234567890777777777777777777777777777777


[(63, 50), (6, 56), (20, 57), (38, 30), (34, 2), (33, 65), (29, 37), (36, 54), (18, 41), (4, 17), (22, 64), (46, 51), (60, 19), (31, 13), (10, 47), (28, 12), (25, 59), (63, 50), (38, 30), (15, 9), (57, 20), (29, 37), (34, 2), (56, 6), (65, 33), (52, 58), (55, 39), (30, 38), (20, 57), (17, 4), (25, 59), (12, 28), (14, 24), (54, 36), (38, 30), (5, 27), (62, 40), (20, 57), (20, 57), (62, 40), (18, 41), (58, 52), (47, 10), (41, 18), (13, 31), (22, 64), (58, 52), (10, 47), (24, 14), (38, 30), (61, 11), (29, 37), (43, 53), (29, 37), (12, 28), (40, 62), (64, 22), (35, 23), (47, 10), (56, 6), (41, 18), (53, 43), (26, 49), (25, 59)]


Selanjutnya, angka pilihan variasi ini diperlakukan sebagai kunci simetris yang rahasia, sedangkan metoda algoritma dan kunci multiplikatif, additif dianggap terbuka. Faktor keamanannya terhadap brute force ialah 1 banding 2.47E+203. Jika dianggap masih kurang memadai, maka bprimes dikalkulasi ulang dengan menambah nilai angka prima **primes = primes_sieve(10000)** pada PROGRAM (8), maka total variasi naik menjadi 2.0E+254  atau medan diubah dan menyesuaikan juga daftar abjad, misalnya menjadi 127, maka panjang bprimes akan bertambah dan total variasi naik drastis.    

Untuk mendapatkan total variasi pengacak diatas 1.0E+1000, maka kita hanya perlu menerapkan metoda pengacak ke tabel kunci additif. Kunci additif misalnya dibuat sepanjang 1063, maka perkalian sebanyak 1063 angka prima bakal mencapai nilai yang sangat besar.

In [111]:
# PROGRAM (10)
# Total variasi dengan penerapan roda modulo pada tabel additif
primes = primes_sieve(10000)
n = len(primes)
bprimes = primes[-1063::]
totalx=1
for n in bprimes:
    totalx *= n

print(f'jumlah digit total variasi {len(str(totalx))}')

jumlah digit total variasi 3889


In [113]:
# PROGRAM (11) Poly-Affine Lengkap
# meningkatkan kemampuan cipher klasik

# setelan konstanta dan inisialisasi tabel-tabel
class Myvar:
    GFIELD = 67 # harus angka prima
    ABJADNYA = 'abcdefghijklmnopqrstuvwxyz,QWERTYUIOPASDFGHJKLZXCVBNM.1234567890?- ' # len(nya) = GFIELD
    PLAINTEKS = "Cipher poly-Affine buatan sendiri ini adalah jenis cipher substitusi polyalphabetic, " \
    "di mana setiap huruf dalam alfabet dipetakan ke padanan numeriknya, "\
    "dienkripsi menggunakan fungsi matematika sederhana, dan dikonversi kembali menjadi huruf. "\
    "Tabel enkripsi faktor pengali dan tabel enkripsi penambah geser yang digunakan dapat dibuat khusus " \
    "berdasarkan nilai kunci simetris, yang rentang jumlah digitnya mencapai tiga ribuan digit (3889)."
    
    def __init__(self,secretnumber):
        p = 1063
        additive_factors = [(1+i)%Myvar.GFIELD for i in range(p)] # default urut, tidak rahasia; atau bisa juga copas dari CSPRNG
        primes = primes_list(10000)
        n = len(primes)
        aprimes = primes[10:10+p]
        bprimes = primes[-p:n]
        secretrange=1
        for n in bprimes:
            secretrange *= n
        secretnumber %= secretrange
        
        self.afactor_tbl = []
        for k in range(p):
            x = (( aprimes[k] * secretnumber ) % bprimes[k] ) % p 
            self.afactor_tbl.append(additive_factors[x]) # TABEL PENAMBAH berdasarkan secretnumber

        mfactor_pairs = []
        for a in range(2,Myvar.GFIELD-1):
            ainv = findModInverse(a,Myvar.GFIELD)
            mfactor_pairs.append((a,ainv))
        self.m1st_len = len(mfactor_pairs)
        self.m2nd_len, self.m3rd_len = add_rotors(self.m1st_len)
        
        primes = primes_list(2022)
        n = len(primes)
        aprimes = primes[10:10 + self.m1st_len]
        bprimes = primes[n-self.m1st_len:n]

        p = self.m1st_len
        new_mkey_pairs = []
        for k in range(p):
            x = (( aprimes[k] * secretnumber ) % bprimes[k] ) % p 
            new_mkey_pairs.append(mfactor_pairs[x])
        self.mfactor_table = new_mkey_pairs # TABEL FAKTOR PENGALI berdasarkan secretnumber
        
        
def mainkan():
    affpoly_teks = "".join(map(polyaffine_encrypt,enumerate(Myvar.PLAINTEKS)))
    print(affpoly_teks)
    teks_aslinya = "".join(map(polyaffine_decrypt,enumerate(affpoly_teks)))
    print()
    print(teks_aslinya)
    
def polyaffine_encrypt(t):
    idx = t[0]
    huruf = t[1]
    p = Myvar.ABJADNYA.find(huruf)
    if (-1 == p): # jika tidak dalam termasuk abjadnya, 
        return huruf # kembalikan tanpa proses
    mfactor = myglob.mfactor_table[idx % myglob.m1st_len][0] * \
              myglob.mfactor_table[idx % myglob.m2nd_len][0] * \
              myglob.mfactor_table[idx % myglob.m3rd_len][0]
    afactor = myglob.afactor_tbl[idx % len(myglob.afactor_tbl)]
    c = ( mfactor * p + afactor ) % Myvar.GFIELD
    return Myvar.ABJADNYA[c]

def polyaffine_decrypt(t):
    idx = t[0]
    huruf = t[1]
    c = Myvar.ABJADNYA.find(huruf)
    if (-1 == c): # jika tidak dalam termasuk abjadnya, 
        return huruf # kembalikan tanpa proses
    mfactor = myglob.mfactor_table[idx % myglob.m1st_len][1] * \
              myglob.mfactor_table[idx % myglob.m2nd_len][1] * \
              myglob.mfactor_table[idx % myglob.m3rd_len][1]
    afactor = myglob.afactor_tbl[idx % len(myglob.afactor_tbl)]
    p = ( mfactor * (c - afactor )) % Myvar.GFIELD
    return Myvar.ABJADNYA[p]

def gcd(a, b):
    while a != 0:
        a, b = b % a, a
    return b

def findModInverse(a, m):
    if gcd(a, m) != 1:
        return None # No mod inverse exists if a & m aren't relatively prime.
    u1, u2, u3 = 1, 0, a
    v1, v2, v3 = 0, 1, m
    while v3 != 0:
        q = u3 // v3 # Note that // is the integer division operator
        v1, v2, v3, u1, u2, u3 = (u1 - q * v1), (u2 - q * v2), (u3 - q * v3), v1, v2, v3
    return u1 % m

def get_key_pairs(gf):
    key_pairs = []
    for a in range(2,gf-1):
        ainv = findModInverse(a,gf)
        key_pairs.append((a,ainv))
    return (len(key_pairs), key_pairs)

def add_rotors(len_satu):
    len_dua = 0
    len_tiga = 0
    for n in range(len_satu,2,-1):
        if gcd(n,len_satu) == 1:
            if 0 == len_dua :
                len_dua = n
                continue
            if 0 == len_tiga and 1 == gcd(n,len_dua) :
                len_tiga = n
                break
    return (len_dua, len_tiga)

from array import array
def primes_list(limit: int) -> tuple:
    # byte array allocation, 1 byte per item for boolean result each
    sieve = array('b', [True] * limit)
    sieve[0] = sieve[1] = False  # zero and one are not prime numbers.
    for start in range(2, int(limit ** 0.5) + 1):
        if not sieve[start]:
            continue
        idx = start ** 2
        while idx < limit:
            sieve[idx] = False
            idx += start
    return [i for i,p in enumerate(sieve) if p]

secretnumber = 0
while not secretnumber:
    secretnumber = int(input("masukan angka rahasia:")) 
myglob = Myvar(secretnumber)
mainkan()


masukan angka rahasia: 1234


CrUG4pVUOySCkh8OdMXS7dFWcQLfW0bTzSyblKsYwl1sqgsD6AZkwG.HgqNUh3xWOjbUhHShBcxFYP2r1pGaj7rE2Tgi34t0UMfcwRcXfV3F0z29yrP ZbN9zMxpGSB?KWfhGSH0 4jbw2149GNwTsxcqKO9rmmInVkIDjQPB1ZjBo,hY.vKhlgNMf9Bw5 RbQLjjFzVwSzPNJ32s5UI0DVMEZl25TIPS6I8cOP0u3dlvaaEaA-RlVC3DUgK0yS-qVljffNutpkLktlQA6hmyGHsBu4PRy3hUyL5.wcwfLls3S7J?iEi8zvZsD4U9tP1EZC-sYmBq1VDDeqGEjgmhzDFYmlYBrEsZXy8MgMlM 6UeC0PUkfg.DC YM5JBbgGPe5 UlXX3VXW6XsuXCJ?BcfDrxVObXiN2cduQx?NFLPYW-3C(vy.a)w

Cipher poly-Affine buatan sendiri ini adalah jenis cipher substitusi polyalphabetic, di mana setiap huruf dalam alfabet dipetakan ke padanan numeriknya, dienkripsi menggunakan fungsi matematika sederhana, dan dikonversi kembali menjadi huruf. Tabel enkripsi faktor pengali dan tabel enkripsi penambah geser yang digunakan dapat dibuat khusus berdasarkan nilai kunci simetris, yang rentang jumlah digitnya mencapai tiga ribuan digit (3889).


Bahasan kita berikut akan menyangkut manajemen kunci simetris yaitu angka rahasia ribuan digit.

Agar memudahkan mengingat memasukkan pin rahasia yang panjang kita dapat mengubahnya menjadi password alfa numerik dan tanda baca.

In [4]:
# PROGRAM (12) Mengkodekan pin menjadi password atau passphrase
class Code9x:
    alnum_95 = "".join([chr(i) for i in range(32,127)])
    alnum94 = alnum_95[1::]

def enc95(number:int) -> str:
    number =  int(number)
    if number == 0:
        return '0'
    kode = []
    while number != 0:
        sisa = number %95
        kode.append(Code9x.alnum_95[sisa])
        number = number // 95
    return ("".join(reversed(kode)))
    
def dec95(kode:str) -> int:
    def digpow(t):
        return Code9x.alnum_95.find(t[1]) * pow(95,t[0])
    return sum(map(digpow,enumerate(kode[-1::-1])))

def enc94(number:int) -> str:
    number =  int(number)
    if number == 0:
        return '0'
    kode = []
    while number != 0:
        sisa = number %94
        kode.append(Code9x.alnum94[sisa])
        number = number // 94
    return ("".join(reversed(kode)))  # kode string output tidak pakai spasi.
    
def dec94(kode:str) -> int:  # kode input tanpa spasi
    def digpow(t):
        return Code9x.alnum94.find(t[1]) * pow(94,t[0])
    return sum(map(digpow,enumerate(kode[-1::-1])))


pwd = input("masukan passphrase:")
pin = dec95(pwd)
print(f'pin Anda {len(str(pin))} digit, yaitu {pin}')
print(f'verifikasi balikan, passphrase : {enc95(pin)}')
 


masukan passphrase: majulah saja


pin Anda 24 digit, yaitu 441915068877311466843345
verifikasi balikan, passphrase : majulah saja


In [86]:
# PRGRAM (13) Menggunakan fungsi hash untuk mendapatkan pin yang panjang dari passphrase yang singkat 
# hash function BLAKE2
from hashlib import blake2b
pwd = input("masukan passphrase:")
barry = bytearray(pwd,'utf-8')
hdig = blake2b(barry).hexdigest()
pin = dec94(hdig)
pin = pin **5 + pin

print(f'pin Anda {len(str(pin))} digit, yaitu {pin}')
# jika ingin melihat passwordnya,
# password tidak mengandung spasi karena kemungkinan luput dari copas jika spasi ada di akhir.
# pword = enc94(pin)
# print(f'kode password: {pword} \nlength {len(pword)}')


masukan passphrase: majulah saja


pin Anda 1260 digit, yaitu 1753925799417370018875468006476720799290490144172534700643578087660419707482669996939927865199888832487663978430763923527164126425462054607518165973460593541172006931474157211725975661955592726966668954024802902522769833096793519322363963822423428280409850602255980459982049867525808610296477993121542115333211415834299158435554237286991541614968429289029813571241183695759161639845846201172686201133573552164517391867753830945751762055277823756741221363199382939818554436989783219859947636211834394448093154526765145197072701330839390428860063700726309711602546264511450910553806395479338579923536935655754351354587614938335446558071738921644587450050618487186209960698688274984198990115741437073380058516238428490020190072668619663733911902107830950671582490130289942890019002136696991632301755665645592072720789629991348689168711209210978670822328955147862822907332574611419335912996195559082157760441935954456173556010242821731976792471464122223153193133443360998613629

Jika Anda memiliki jalur yang dipercaya aman maka passphrase rahasia dapat dikomunikasikan dengan mitra, lalu Anda dapat mengirim pesan yang terenkripsi lewat jalur internet/email yang publik. Masalahnya, setiap kali mengirim pesan, enkripsi harus berbeda tidak boleh mengulang pola yang sebelumnya karena ada resiko penyadap bisa menyimpan beberapa pesan lalu melakukan analisa pemecah kode. Artinya pin rahasia harus berubah unik setiap kali melakukan enkripsi/dekripsi.   

Mari perhatikan bahwa dengan menambahkan header tanggal-jam kita dapat memodifikasi pin rahasia setiap kali mengirim pesan, tetapi passphrase rahasia hanya sekali saja dikomunikasikan lewat jalur yang aman. 

In [134]:
# PROGRAM (14) Mengedit pin rahasia dengan header date-time
# sebagian definisi diambil dari Program (11)
from hashlib import blake2b
import datetime as dt
def makepin(pass_string: str) -> int:
    barry = bytearray(pass_string,'utf-8')
    hdig = blake2b(barry).hexdigest()
    pin = dec94(hdig)
    return pin **5 + pin
def dt_now():
    x = dt.datetime.now()
    return x.strftime("%Y%m%d%H%M%S")

plainteks = Myvar.PLAINTEKS #input('input pesan yang akan di-enkripsi:')
pwd = "majulah saja" # input("passphrase yg sudah disepakati lewat jalur aman:")
header = dt_now()
secretnumber = makepin(header+pwd)
myglob = Myvar(secretnumber) # pastikan Program (11) sudah di-run, dan masih ada di memori 
affpoly_teks = "".join(map(polyaffine_encrypt,enumerate(plainteks)))
print(header+affpoly_teks)

print()
print('deskripsinya')
teks_diterima = header+affpoly_teks
header = teks_diterima[0:14]
ciphered = teks_diterima[14::]
# pwd = input("passphrase yg sudah disepakati lewat jalur aman:")
secretnumber = makepin(header+pwd) #pwd kesepakatan sama

teks_aslinya = "".join(map(polyaffine_decrypt,enumerate(ciphered)))
print(teks_aslinya)
print()
print("SILAHKAN DIRUN BERKALI KALI DAN LIHAT PESAN YANG DIENKRIPSI BERUBAH UBAH (per detik) WALAUPUN PESAN ASLINYA SAMA")

20220322195940ThjWD5d1dh,uoJy6S5Mh6sffrP3maK6vA0kWixs4O,5XAwU-d.PmOQHll2 o4vDU7po-7vvDr8fU7hneU76HRzWOCQrISoRZbNAkS5oJooNm6KFe6vBc0tyQsrfdg.GcNuNje-e8.0NVI.QOty-tJUeLQZcpLEp7bo,480bZ2AWrv70q0R4mjvq9uhdeg5Y?sKox?AINwBhLJi2s1erXJB?f44C.uQ6.PP4n9ZBuY0?0OFFfT3hvY  rAOSC,gCMsAn-HNVhGMf3Q4QMNwmD2N3S ,5TWQpG8pD-ukQ,XRT.KK0LioxmzFY vaHTSeX.?WhoHbsDcq7dRHMKBo,0DAx4aYmMctR,VNj dhhsq6cd8wGUh6qQBg.UP8.W3qpeEV?lNCvXG?ZjmZ2JvVOT0pcA0?DaRBnd2wweSR,V3mDdE3De(jSpm)p

deskripsinya
Cipher poly-Affine buatan sendiri ini adalah jenis cipher substitusi polyalphabetic, di mana setiap huruf dalam alfabet dipetakan ke padanan numeriknya, dienkripsi menggunakan fungsi matematika sederhana, dan dikonversi kembali menjadi huruf. Tabel enkripsi faktor pengali dan tabel enkripsi penambah geser yang digunakan dapat dibuat khusus berdasarkan nilai kunci simetris, yang rentang jumlah digitnya mencapai tiga ribuan digit (3889).

SILAHKAN DIRUN BERKALI KALI DAN LIHAT PESAN YANG DIENKRIPSI BERUBAH UBAH (per detik) WALAUP

Guys, sampai disini dulu contoh program Python dalam kasus kriptografi khususnya modifikasi Affine cipher. Enjoy!   

Mungkin lain kali kita diberi kesempatan membahas protokol Diffie-Hellman untuk komunikasi lewat jalur publik yang tidak aman, sehingga bahkan untuk kesepakatan kunci simetris sekali saja, terpaksa digunakan metoda kunci asimetris. Sinau mas.
